# Generated by Django 4.2.5 on 2023-09-05 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('laborid', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipocultivo',
            fields=[
                ('tipocultivoid', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipoCultivo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='productor',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Vivero',
            fields=[
                ('viveroid', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('tipocultivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productor.tipocultivo')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoControl',
            fields=[
                ('productocontrolid', models.AutoField(primary_key=True, serialize=False)),
                ('registroICA', models.CharField(max_length=30, unique=True)),
                ('nombreproducto', models.CharField(max_length=50)),
                ('frecuenciaDias', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productor.labor')),
            ],
        ),
        migrations.AddField(
            model_name='labor',
            name='vivero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productor.vivero'),
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('fincaid', models.AutoField(primary_key=True, serialize=False)),
                ('numeroCastro', models.IntegerField()),
                ('municipio', models.CharField(max_length=50)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productor.productor')),
            ],
        ),
        migrations.CreateModel(
            name='ControlPlaga',
            fields=[
                ('controlplagaid', models.AutoField(primary_key=True, serialize=False)),
                ('diasPeriodoCarencia', models.IntegerField()),
                ('productocontrol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productor.productocontrol')),
            ],
        ),
        migrations.CreateModel(
            name='ControlHongo',
            fields=[
                ('controlhongoid', models.AutoField(primary_key=True, serialize=False)),
                ('diasPeriodoCarencia', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('productocontrol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productor.productocontrol')),
            ],
        ),
        migrations.CreateModel(
            name='ControlFertilizantes',
            fields=[
                ('controlfertilizantesid', models.AutoField(primary_key=True, serialize=False)),
                ('fechaUltimaAplicacion', models.DateTimeField()),
                ('productocontrol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='productor.productocontrol')),
            ],
        ),
    ]
